version: '3'
services:
    mysql-sr:
        build: ./mysql
        container_name: mysql-server
        command: --default-authentication-plugin=mysql_native_password --sql_mode=""
        restart: always
        environment:
        - MYSQL_ROOT_PASSWORD=je6H92Gagf91Ha
        - MYSQL_DATABASE=tacocon
        networks:
            - backend
    web-server:
        build: .
        ports:
            - "8234:80"
        depends_on:
            - mysql-sr
        networks:
            - backend

networks:
    backend:
        driver: bridge